logger: 
  level: debug
  devMode: true
http: 
  port: :8081
postgres:
  connectionString: "postgres://user:password@localhost:5432"
  db: nftvc
redis: 
  uri: "localhost:6379"
mongo:
  uri: mongo://user:password@localhost:27017
nonce:
  exp: 900s
mongoCollections:
  accounts: accounts
  refreshTokens: refreshTokens
